version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - serverIP=192.168.1.187
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=JefferySynoDS920
      - auth=false
      - openBrowser=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /volume2/docker/tdarr/server:/app/server
      - /volume2/docker/tdarr/configs:/app/configs
      - /volume2/docker/tdarr/logs:/app/logs
      - /volume2/docker/tdarr/transcode_cache:/temp
      - /volume1/Media/media:/media
    network_mode: bridge
    devices:
      - /dev/dri:/dev/dri
