---
version: "2.1"
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - DOCKER_MODS=linuxserver/mods:plex-absolute-hama
    volumes:
      - /volume2/docker/plex/config:/config
      - /volume1/Media:/data
        # Mount the transcode directory to the tmpfs volume
      - transcode_temp:/transcode
    network_mode: host
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

volumes:
  transcode_temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=6g,uid=${PUID},gid=${PGID}
