version: "3.6"
services:
  requestrr:
    container_name: requestrr
    hostname: requestrr
    image: thomst08/requestrr
    restart: unless-stopped
    ports:
      - 4545:4545
    volumes:
      - /volume2/docker/requestrr/config:/root/config
    network_mode: bridge
