version: "3.5"

services:
  dash:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "3001:3001"
    volumes:
      - /:/mnt/host:ro
