 version: '3'

 services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      # - JELLYFIN_PublishedServerUrl=192.168.1.240 #optional
    volumes:
      - /volume1/docker/jellyfin/config:/config
      - /volume1/Media/media:/bigdata/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
#     - 1900:1900/udp #optional
    restart: unless-stopped
